# Question 2

This code snippet makes a fetch to get the first todo item from the JSON placeholder API. Or at least it tries to.

What is wrong with this code?

Describe how async/await helps us avoid this mistake.

```js
fetch('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => {
    if (!response.ok) throw new Error('Fetch failed!');
    response.json();
  })
  .then(json => console.log(json))
  .catch(err => console.log(err))
```

You can run this code of course, but try not to! Try to figure out the issue on your own.

# Answer
The problem with the provided code snippet is that the `response.json()` in the first `.then()` block isn't being returned, thus not chained. As a result, the second `.then()` block doesn't receive the parsed JSON data but will instead receive a promise resolved with the value `undefined` and log it.

`async`/`await` helps us avoid this mistake by its design, not requiring any chaining at all. Below is how the same code exact would be structured using `async`/`await` syntax:

```js
try {
  const response = await fetch('https://jsonplaceholder.typicode.com/todos/1');
  if (!response.ok) throw new Error('Fetch failed!');
  const json = await response.json();
  console.log(json);
 }
catch (err) {
  console.log(err);
}
```

With `async/await`, we don't have to worry about returning promises explicitly or chaining `.then()` blocks, making the code more intuitive and less error-prone. We can just *wait* until the promise has resolved, saving its result to a variable.

# Teacher Feedback
Score: 3/3